name: web_page_runner
description: A runner application for Rapider web pages.
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  rapider_sdk:
    path: ../../packages/rapider_sdk
  rapider_page_contract:
    path: ../../packages/rapider_page_contract
  rapider_ui:
    path: ../../packages/rapider_ui
